controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /home
    controller: App\Controller\HomeController::index
connexion:
    path: /
    controller: App\Controller\ConnexionController::index
checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::index
commande:
    path: /commande
    controller: App\Controller\CommandeController::index
commande_statut:
    path: /commande/statut/{id}
    controller: App\Controller\CommandeController::statut
    methods: GET